language: python
python:
  - "2.7"
install: pip install tox-travis python-coveralls
script: tox
after_success: coveralls

deploy:
    # test pypi
  - provider: pypi
    distributions: "sdist bdist_wheel"
    server: https://testpypi.python.org/pypi
    user: theidledeveloper
    password:
      secure: "X75BVy4vgPlmcpEMYP48dVOMFrVwJxBgpOx9FQI4S9GAThsgHubBugWKtYUXkxWJ3TCgkIiHGZBAP1qnRjKjCPPLuw5q8Ndx2xd6VlLQmiwvlDYH/MjnJ/bDIQa3eOs7pzZ6d07SaVgg5uEpnva+5ApX/LPEBajb1UA/XtkbN/3mD+HExZdPJriYK0ovXXuusVW6ZEgR5nh4J8U2JOTr5x+AOuXhdM/9fqRBff0y1mZ6lHJXCJ6PqV0tZgEh1/EkjJaZERvQzjDhtmwual9KEUfUU4vqOwfnbp04C5PpxJH9J3Ya7r1Jh+Xa72ahCAbToFFM0EfX5jevPds8fzu5qbCIkJ6nM3gt2EzBTOv6gDHXIyXoTg8cgaIRQXpDvjyHsscsOU6o9cx6izbOtS6hP+BJJ9wjRcXbqvDlAxPOfyXGV8j7uR7l0X9u6sWC6hE6F0+s0OMr+GX74ctnEQ3k/ojDzNEwg3GPM4ceXTgbaf6IqJaEQvE00Ewc4Cib5eOf+MJWteKIbdqXbGgL7s5GoH1aZw91SiMb/WgdlOyuw89PfM61BmYLwFx8uutAnrCQxCR36YEloIRbwn3Src00dVYnXwdvZMrDw9Ic0ZPVNoxlxeWQo8V9Q7uTlAUm2TdWMLghxqmLkVwRTJ3ERQcbH0DoZRbz7wlNkM7w6d0VEKQ="
    on:
      branch: master
      tags: false
      repo: theidledeveloper/s3-cmd-website
      condition: $TRAVIS_PYTHON_VERSION = "2.7"

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: theidledeveloper
  password:
    secure: "GeANSzCac2CLmbP5rXfUl9gwV10U9Ck0lu8HXo9EvUhhu4oDRHPLGjWyirAGbreoLKzLY8qEnWkg1i/3aHn9C6Wno6REJWCykPQN8IyGnMisXnm9LIrZ1BlDmMHA1NiQpvrzn0VjJr7yxDwE9VouuZ9LIwG/oRxqvhne7dFgBa/fWSbcqYbcxulMna5ZhAABKtJxeXS4GPxAhHXuPdnP3Sj+rTlqqKO706vOFC1DJTw7v95lM0LGs5Se0Uj/AikVCa8IpGfRelubFcKPv41u5+lC/etAMjWrVMprpYLQEO6KQnRhtR0ePwGF9tU8LJJE5r5GlEIPGXpPCYm1KDLhfGr5mQXxBtqGZxQWOB3rvZUPSZZ8NIy9suZzz7MVjcrsZvluVI/JPnO/6BfPPoZN7NGl5qHYwt3n4AwLAhjHjdgWMeT0NqricD3mPmwHe/5RqWf2dLAdXIwbI9j5so8R4UsD85bNlmd6bI4rGIV19FEsP5qvB5rCcOvtDUzNXcAS9S6DnPdfRMDMUHWFGkYSbNh2gc3oOwZtO77iGMM/pAthHFF1S/nqjYFnxXRPCeMZ87lu6ON5LiCUg9YX5cwHVbut0Ry20RLchLKKBFGe9Vi+o/ZO0W3QxK9QGbURdRLG2IW2lQev6c1Tlc/K/06ebUdOxU8vqXjbAWZxmHp05kY="
  on:
    tags: true
    branch: master
    repo: theidledeveloper/s3-cmd-website
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
